# Generated by Django 4.2 on 2024-05-09 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gelatina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelatina_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('descipcion', models.TextField()),
                ('imagen', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
        ),
    ]
